### ISSUE TITLE
2 different Foregoing Essences

### ISSUE THREAD

**Issue by JFMillerUSA** [NillerMedDild/Enigmatica2#182] opened 2018-11-27 19:24 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I have a Basic Portable Tank(Thermal Expansion) and Basic Fluid Tank(Mekanism) with Industrial Foregoing Essence, and cannot empty into a Black Hole Tank with Essence already in it.

**Modpack version (Do not use "latest")**
1.53

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

I've tried to use buckets in the Basic tanks which are the same and a bucket from the Black Hole tank which titled the same but are different, either bucket will not dump in others tank.

**Comment by NillerMedDild** [comment] 2018-11-28 05:29
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2018-12-11 09:19
I cannot reproduce this, so I'm guessing it was fixed by the dev.

**Closed by NillerMedDild** 2018-12-11 09:19 UTC
Labels: cannot reproduce
