### ISSUE TITLE
Picking up redstone is slow

### ISSUE THREAD

**Issue by LibertyGTX** [NillerMedDild/Enigmatica2#699] opened 2020-12-16 02:01 UTC
**Modpack version**
Enigmatica2-1.77

**Issue**
I made a server on my laptop to play solo. Everything works perfectly,  but when i mine redstone ore , it takes a few seconds to pick it up. Only applicable for redstone ore. Also the server is flooded with a warning.

**Logs**
Here is the warning i get in my server console ONLY when i mine redstone ore:
https://mystb.in/VolumesPacMailing.less

Note: if i vein mine a big redstone ore vein , the server also restarts itself.
EDIT: Someone on discord said they experience this issue on singleplayer , so it is not a server-side issue.
EDIT2: did a fresh client reinstall , and went on singleplayer to test it. Mining redstone lags the world and it takes 2-3 seconds to pick up the redstone.

**Comment by NillerMedDild** [comment] 2020-12-16 19:52
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2021-03-06 20:47
Duplicate of #663

**Closed by NillerMedDild** 2021-03-06 20:47 UTC
Labels: Bug
