### ISSUE TITLE
Crashing while exploring log attached.

### ISSUE THREAD

**Issue by GldnSabre74** [NillerMedDild/Enigmatica2#103] opened 2018-10-02 19:42 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
While exploring the overworld in SP my game will crash.

**Modpack version (Do not use "latest")**
1.47
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/2439427/latest.log)

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment] 2018-10-03 06:03
Can you reproduce this issue without Optifine?

**Comment by neoc666** [comment] 2018-10-06 08:33
While I heard that optifine can cause problems, I found that optifine is the only way to get acceptable performance (my PC is fine for many games, I have 12GB RAM, with 6GB assigned to Minecraft). It's a huge difference. I too had a random crash and I'm also using optifine. I did not change optifine settings to be more aggressive in any way, it should be pretty much the default settings.

Is optifine deprecated in any way? Is it impossible to tell from the log if optifine was the reason for the crash?

**Comment by NillerMedDild** [comment] 2018-10-06 13:51
I can't be sure that Optifine is the cause, but I've seen this issue reported several times, never by a person not using Optifine.

With 6GB allocated RAM, you should be fine really - Are you using Jar Launcher, in order to use your PCs newest Java? By default Twitch uses the Java that comes with Minecraft, which is ooooold.

**Comment by neoc666** [comment] 2018-10-06 13:56
I always use the Twitch launcher. I hate it, but I didn't get around using an alternative so far because I usually don't trust anyone ;) Maybe I should finally find a replacement for it.

Is Java version really that important? And for performance? Because it's really bad. I tried SevTech and it was almost unplayable with lag spikes and FPS often < 20. Almost every time I engage a mob I get a tiny lag spike so I can never be sure that I hit the mob first and get the knockback... not fun at all. Optifine was helping with that, at least regarding FPS and overall performance.

**Comment by NillerMedDild** [comment] 2018-10-06 13:57
Java version is extremely important for performance and stability.

I like the Twitch launcher, you just gotta get it set up correctly :)

**Comment by neoc666** [comment] 2018-10-06 14:00
Thanks, I will give it another try. Was almost done with Minecraft because of all the issues... back to modded Factorio, which is excellent regarding performance and stability.

**Comment by NillerMedDild** [comment] 2018-10-06 15:50
The default JVM settings work just fine for me :) I recommend that you don't change them unless you know what you're doing.

Yes, by choosing Jar Launcher. Let it load for a while, maybe close/open it a few times, it can take ~10 seconds to sync the first time.

**Closed** 2018-10-17 06:37 UTC
Labels: invalid, more-information-needed, other mod
