### ISSUE TITLE
Recipes not working.

### ISSUE THREAD

**Issue by Kirbyarm** [NillerMedDild/Enigmatica2#316] opened 2019-02-11 10:19 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

Certain recipes that are in JEI, and upon further investigation, in the modpack's .ZS scripts files, aren't producing any items into the result slot of crafting stations as they should.

It appears two scripts aren't loading correctly on my server and MorganSimic believes since something error'd out on those two scripts, the entire script's recipes will not work. The recipes in question (such as Lonsdaleite crystals from E.T.) do in fact fall into these scripts and do not work.

**Modpack version (Do not use "latest")**

TwitchApp version 1.58

**Logs**

N/A

**Screenshots**

https://i.imgur.com/h06C6VY.png

**Additional context**

Here are the two unchanged, untampered with .ZS files that seem to be causing the issue.

https://www.dropbox.com/s/59n73aalduzjl0o/MiscRecipes.zs?dl=0
https://www.dropbox.com/s/2zbq8bcuenk134e/RecipeConflicts.zs?dl=0

**Comment by NillerMedDild** [comment] 2019-02-11 11:18
Weird, I didn't notice any script errors when I  made update 1.58. You didn't remove the mod PlusTiC right?

**Comment by NillerMedDild** [comment] 2019-02-11 17:35
Probably duplicate of #315

**Closed by NillerMedDild** 2019-02-11 17:35 UTC

**Comment by MorganSimic** [comment] 2019-02-11 17:58
I did discuss this at length on discord. From all I know this issue does not happen to everyone. And this was clean install without any mod updates. Downloaded as is from Twitch. Moar tinkers was added, but the issue continued without the mod.

**Comment by NillerMedDild** [comment] 2019-02-11 18:17
The reason for this issue was the abscence of Invar materials from PlusTiC - PlusTiC most likely turns off Invar compatibility when in the same instance as Moar Tinkers, so there are not duplicate Tinkers materials.

**Comment by Kirbyarm** [comment] 2019-02-11 18:48
Assuming it was MoarTinkers causing PlusTiC to turn off the invar compatibility as you believe, wouldn't that mean when MoarTinkers is removed for a test that the recipes script would not remain broken during the test specifically geared towards seeing if it was that mod causing it or not? Hmm.

**Comment by NillerMedDild** [comment] 2019-02-11 18:52
Yeah I don't know why removing it didn't help.
