### ISSUE TITLE
Items Disappearing from Inventories, Unable to Use Items

### ISSUE THREAD

**Issue by ecorn85** [NillerMedDild/Enigmatica2#493] opened 2019-06-09 16:28 UTC
**Modpack version**
1.67d

**Can the issue be reproduced?**
I can reproduce the issue on my world, I do not know if it is reproducible by others.

**Issue**
I am not sure if the issues are related, but

1. When viewing the items in an inventory, the inventory will suddenly clear and act like there no items in slots when I try to add/remove items. I have to exit the ui and open the inventory again to see the items. However, the items "disappear" again after a few seconds. This has been prominent with the Iron Chest Diamond Shulker Boxes and Thaumcraft Inscription Table's ink and paper slots. I do not have any issues with normal chests, shulker boxes, or diamond chests. It could affect more items than these, but this is what I have encountered.

2. After prolonged game time I appear to be unable to right click and use items such as loot boxes or eat food. I have tried with both an empty and filled off hand, but was had the same issue. The loot box would be "used" but I would receive no reward, then eventually the loot box would end up back in my inventory. The food would never finish the eating animation or use up the item.

**Comment by NillerMedDild** [comment] 2019-06-09 16:33
Thanks for the report. I would like your latest.log so I can investigate the issues you're experiencing.

Are the inventories you're experiencing bug 1 on in the same chunk or area? If yes, are they near a Tinkers' Construct Smeltery?

**Comment by ecorn85** [comment] 2019-06-09 16:48
[latest.log](https://github.com/NillerMedDild/Enigmatica2/files/3269751/latest.log)

I logged in and checked, yes the inventories are in the same chunk, and it is the same chunk as a Tinker's Smeltery. The smeltery is above and my base is in a cave below. I brought one of the diamond shulker boxes out to a different chuck and the inventory is not disappearing.

**Comment by NillerMedDild** [comment] 2019-06-09 17:08
Cool, that particular bug should be fixed in the next update of the pack, it was a mod interaction.

**Comment by NillerMedDild** [comment] 2019-06-09 17:09
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

Please see if that resolves issue #2

**Closed** 2019-06-16 17:49 UTC
Labels: Status: Awaiting Information, Type: Bug
