### ISSUE TITLE
Block of Steel in Advanced Thermionic Fabricator Structure isn't OreDict

### ISSUE THREAD

**Issue by BuggaNoia** [NillerMedDild/Enigmatica2#413] opened 2019-03-31 11:20 UTC
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes: As long as you use the "wrong" Block of Steel type gives a 'structure incomplete'

**Issue**
More an annoyance than an issue: The Advanced Thermionic Fabricator required Immersive Engeneering Block of Steel (# 8679/8). Crafting 9 Steel into a block gives a Thermal Foundation Block of Steel (# 4690/0). 
In game it can be easy fixed with a chisel, but if you not aware of it, you wonder for some time, why the structure considered 'incomplete' as long as the wrong type of steel block is in it.

Suggestion: Change the Modular Machinery structure to accept both types. (As it already does with Mana Infused vs. Platinum Infused Hardenend Glass.)

**Comment by MaxNeedsSnacks** [comment] 2019-03-31 11:42
Duplicate of Enigmatica2Expert#650

**Comment by BuggaNoia** [comment] 2019-03-31 12:04
> 
> 
> Duplicate of [NillerMedDild/Enigmatica2Expert#650](https://github.com/NillerMedDild/Enigmatica2Expert/issues/650)

Upps my fault

**Closed** 2019-03-31 12:53 UTC
Labels: Type: Duplicate
