### ISSUE TITLE
AE2 Universal Crafting terminal bug

### ISSUE THREAD

**Issue by zanikoleh** [NillerMedDild/Enigmatica2#364] opened 2019-03-04 07:47 UTC
**Modpack version**
1.59

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/NqmtyCMY

Crash message:
The game crashed whilst rendering entity in world
The game crashed whilst rendering entity in world
Error: java.lang.AbstractMethodError: Method extracells/item/ItemWirelessTerminalUniversal$.getRender()Lp455w0rd/ae2wtlib/api/client/IBaubleRender; is abstract

**Issue**
Shift + Left Click on universal wireless terminal with opened baubles view. When load save, open inventory, causes game crash.

**Comment by NillerMedDild** [comment] 2019-03-04 09:19
duplicate of #327 

Sorry for the inconvinience. You can edit the Terminal out with NBTExplorer, or delete it with a `/bauble` command.

**Closed by NillerMedDild** 2019-03-04 09:19 UTC
Labels: duplicate
