### ISSUE TITLE
Changing volume while inventory is opened moves the hotbar.

### ISSUE THREAD

**Issue by d-avery** [NillerMedDild/Enigmatica2#703] opened 2021-01-13 13:06 UTC
**Modpack version**
Enigmatica 2 1.77

**Issue**
Changing volume while inventory is opened moves the hotbar.

This includes changing the volume with keyboard shortcuts (like Fn+F10/F11, on my keyboard) or mouse shortcuts (i.e. I have my G7/G8 buttons on my Logitech G502 set to volume up/down)

I frequently change my volume to check if someone is trying to talk to me in real life. It's annoying that changing the volume messes up my inventory. What is causing this issue?

**Logs**
Not applicable.

**Comment by NillerMedDild** [comment] 2021-01-13 21:47
Thanks for the report! This seems to happen randomly from time to time, sadly - You need to bind or rebind the cycle hotbar hotkey(s) from Cyclic.

duplicate of #98

**Comment by d-avery** [comment] 2021-01-13 21:58
Thank you for your quick response, I will make sure to try this solution next time I play. Have a great day.

**Comment by d-avery** [comment] 2021-01-14 13:42
Okay. I just tried this. Turns out, it wasn't a keybinding specifically, but it was an option inside Cyclic's Mod Options config, under the inventory category, I had to set "KeybindInventoryShift" to false to fix my issue. Hope this helps anyone reading this.

**Closed** 2021-03-06 22:16 UTC
Labels: Bug, Status: Fixed In Next Release
