### ISSUE TITLE
[Feature Request] Add mod Railcraft 

### ISSUE THREAD

**Issue by Landrash** [NillerMedDild/Enigmatica2#349] opened 2019-02-20 15:38 UTC
**Modpack version**
1.59

**Feature Request**
Addition of mod.
Reason is simple. In the current iteration there's few things that encourage building over a wide area.
The addition of [Railcraft](https://minecraft.curseforge.com/projects/railcraft/) can be used as a transport system over a wider area if promoted at early gameplay.

**Comment by NillerMedDild** [comment] 2019-02-20 18:05
Duplicate of #263

**Closed by NillerMedDild** 2019-02-20 18:05 UTC

**Comment by Landrash** [comment] 2019-02-20 19:05
Terribly sorry about that. Must have missed it when searching.

**Comment by NillerMedDild** [comment] 2019-02-20 21:00
That's alright :)
