### ISSUE TITLE
Random Villager sounds in chunks near villages. (1.66)

### ISSUE THREAD

**Issue by Aeka80** [NillerMedDild/Enigmatica2#452] opened 2019-05-01 02:50 UTC
**Modpack version**
1.66

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
When near a village, villager sounds will randomly play from an area close to the player, even when no villagers are nearby. The sounds play right next to the player every few seconds and makes it irritating to be anywhere within 10 chunks of a village. Tried relogging and restarting, with no remedy. Happens consistently within a decent range of any village.

**NOTE:** In case it matters, I have Wizardry downgraded to 0.9.9 (as opposed to 0.10.0 that is in v1.66 by default) to avoid crashes mentioned in #450 and #451.

**Comment by NillerMedDild** [comment] 2019-05-01 05:39
Thank you for the report, I will investigate the issue.

**Comment by Dephyantx** [comment] 2019-05-03 17:27
I've had the same issue in the recent version of Enigmatica 2 light 1.22. Wasn't near a village but I hear villager sounds in random areas.

**Comment by CatnipTheGrey** [comment] 2019-05-04 08:06
I've the same issue on Enigmatica 2 Light 1.2.2, even far away from villages

**Comment by NillerMedDild** [comment] 2019-05-04 18:33
I have no idea what could be causing this issue to be honest.

**Comment by NillerMedDild** [comment] 2019-05-04 18:36
Aha! I believe this is caused by Quark, and should be resolved in future updates. Please let me know if the issue persists in the new update (should be out within 3 days)

**Closed** 2019-05-07 08:05 UTC
Labels: Status: Confirmation Needed, Type: Mod Issue

**Comment by Aeka80** [comment] 2019-05-08 06:36
Tried out a new world on 1.66b and the problem still persists, only it seems to happen in random areas now, not only near villages. Had it happen on an island with nothing but water around, and no villages around any nearby shores. The sounds seemed to be centered on a Quark-related cave system and ravine, as both are filled with cave roots and crystals from Quark. The sounds played on any surface within, below, or above the caves and ravine, no matter the Y level. Thank god for sound mufflers.
