### ISSUE TITLE
Better Questing Loot Chests Open to "null"

### ISSUE THREAD

**Issue by Warped2pt0** [NillerMedDild/Enigmatica2#590] opened 2019-12-06 02:48 UTC
**Modpack version**
Enigmatica 2 v2.174

**Issue**
Upon receiving Loot Chest from quest reward, you will receive "null" when opening the chest. Tested this with all chests and only the "dungeon" and "set" chests give items. The rarity 0, 25, 50, 75, 100 and ??? chests all result in "null".

**Logs**
Found this in my latest log:

[21:44:23] [Client thread/FATAL] [net.minecraft.client.Minecraft]: Error executing task
java.util.concurrent.ExecutionException: java.lang.ArithmeticException: / by zero
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1088) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ArithmeticException: / by zero
	at bq_standard.client.gui.GuiLootChest.initPanel(GuiLootChest.java:44) ~[GuiLootChest.class:?]
	at betterquesting.api2.client.gui.GuiScreenCanvas.func_73866_w_(GuiScreenCanvas.java:120) ~[GuiScreenCanvas.class:?]
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478) ~[blk.class:?]
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:1018) ~[bib.class:?]
	at bq_standard.network.handlers.NetLootClaim.onClient(NetLootClaim.java:59) ~[NetLootClaim.class:?]
	at bq_standard.network.handlers.NetLootClaim$$Lambda$6149/1418927827.accept(Unknown Source) ~[?:?]
	at betterquesting.network.PacketQuesting$HandleClient.lambda$onMessage$0(PacketQuesting.java:114) ~[PacketQuesting$HandleClient.class:?]
	at betterquesting.network.PacketQuesting$HandleClient$$Lambda$6903/694390407.run(Unknown Source) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]
	... 9 more

**Comment by NillerMedDild** [comment] 2019-12-06 07:58
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

Please let me know if that resolves the issue :)

**Comment by NillerMedDild** [comment] 2019-12-08 18:32
- This issue can be fixed by running the command `/bqs_loot default load` - You need to be OP, or the single player world creator :)

**Closed** 2019-12-13 08:22 UTC
Labels: Status: Awaiting Information
