### ISSUE TITLE
Better Questing Parties:

### ISSUE THREAD

**Issue by infaerina** [NillerMedDild/Enigmatica2#88] opened 2018-09-08 15:36 UTC
#### Enigmatica 2, v. 1.46

I am unable to create a new party in the Better Questing mod. When opening the party menu clicking under name, immediately unselects "New Party" and any changes I have made by spamming the keyboard buttons have no effect. Clicking on Create Party has no effect either.

**Comment by NillerMedDild** [comment] 2018-09-09 06:32
Are you sure this was on 1.46? I thought it was fixed by the update.

**Comment by infaerina** [comment] 2018-09-09 18:36
Yes, both my client and server are on 1.46. The other two people on the server cannot create parties either. We have the client side pack from Twitch, but it is labeled 1.46 as well.

**Comment by NillerMedDild** [comment] 2018-09-10 16:44
I'm working on update 1.47 at the moment, please let me know if the issue is resolved for you in that version. It should be available within an hour.

**Comment by NillerMedDild** [comment] 2018-09-11 07:36
Awesome! Thank the mod dev, I just updated :b

**Closed by NillerMedDild** 2018-09-11 07:36 UTC
Labels: waiting for author
