### ISSUE TITLE
1.52 Update causes massive lag multiplayer

### ISSUE THREAD

**Issue by MechanosG** [NillerMedDild/Enigmatica2#168] opened 2018-11-16 06:26 UTC
_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
After we updated our server to 1.52, we experienced a strange latency lag of sorts.  But only when 2 or more players were connected at once.  Attempting to chat would result in a couple minute delay before the message goes through, breaking blocks had a massive delay, inventories weren't syncing, etc.  Client side FPS was unaffected, and the server owner didn't report anything strange being in the console.  If all players left except for 1, strangely most of the lag would go away.  You could chat for example, and the text would come up quickly as per normal, and break blocks without problem.

Reverting back to 1.51 fixed the issue.

**Modpack version (Do not use "latest")**
1.52

**Logs**
Server owner reported nothing of interest being in the log, but I don't have access to it to say for sure.  I didn't think to grab my client log.

**Screenshots**
N/A - everything looks normal

**Additional context**
At first we thought maybe the ISP on the server end was having issues.  But after doing some speed tests on various sites, he was getting about 43mbps download on average.  And after reverting to 1.51 the problem went away.  So I'm somewhat certain something in the update is causing problems.  I'm just not sure what.  Hopefully the fact that the lag went away when you're the only person on server, might give a hint towards what might cause it?

**Comment by jinkhya** [comment] 2018-11-16 07:58
https://github.com/NillerMedDild/Enigmatica2/issues/149
Looks like it could be this. Check how much bandwidth your client is using and if it looks like about 1Mbps per player connected then it's that issue caused by betterquesting.

**Comment by NillerMedDild** [comment] 2018-11-16 08:30
duplicate of #149

**Closed by NillerMedDild** 2018-11-16 08:30 UTC
