### ISSUE TITLE
[1.61] Quests not completing

### ISSUE THREAD

**Issue by nodey420** [NillerMedDild/Enigmatica2#383] opened 2019-03-09 09:45 UTC
**Modpack version**
1.61

**Can the issue be reproduced?**
Yes

**Logs**
NA

**Issue**
None of the quests I am working on recognize that I have the pre-requisites for them.

"Wooden Sheers"
"That's a lot of ingots.."
"Oxydizing Sulfur"
"By the power of the sun!"

I tried to do a /bq_admin default load but that did not resolve the issue.

**Comment by NillerMedDild** [comment] 2019-03-09 09:46
Duplicate of all the other quest completion issues.

**Closed by NillerMedDild** 2019-03-09 09:46 UTC
