### ISSUE TITLE
Backpack mod recipe issue

### ISSUE THREAD

**Issue by Painstouch** [NillerMedDild/Enigmatica2#508] opened 2019-07-01 16:40 UTC
**Modpack version**
1.67d

**Can the issue be reproduced?**
Yes

**Logs**
No crash

**Issue**
STONE STICK cannot be crafted for the recipe STONE FRAME, which is need for crafting Big Backpack and others.
![javaw_HohYYQKL4B](https://user-images.githubusercontent.com/5760220/60452779-a0ff6980-9c2f-11e9-8273-63ee167d765f.png)

**Comment by NillerMedDild** [comment] 2019-07-01 16:43
Duplicate of #423

**Closed by NillerMedDild** 2019-07-01 16:43 UTC
