### ISSUE TITLE
Unable to complete certain Mekanism quests

### ISSUE THREAD

**Issue by taiyoko** [NillerMedDild/Enigmatica2#567] opened 2019-09-27 18:43 UTC
**Modpack version**
1.72

**Can the issue be reproduced?**
unknown

**Issue**
Certain quests refuse to detect the item to complete them, possibly metadata-related like in past issue 469? I haven't completed all of the quests available in Mekanism so far yet, so there may be others that I haven't found yet.

Quests and items affected:
- Mekanism Part 1
  - Smashing The Power > Crusher
  - Becoming Better > Advanced Energy Cube
- Mekanism Part 2
  - Changing the state of matter! > Rotary Condensentrator
  - Dustifying lithium > Chemical Crystallizer

**Comment by NillerMedDild** [comment] 2019-09-27 19:15
Duplicate of #544

**Closed by NillerMedDild** 2019-09-27 19:15 UTC

**Comment by NillerMedDild** [comment] 2019-09-27 19:16
However we have resolved some of the Mekanism quest issues, please use the command `/bq_admin default load` and check if that resolves the issue.
